version: "3.4"
services:
  mydb:
    build:
      context: .
      target: db
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432

  web:
    build: 
      context: .
      target: web_api
    container_name: infinity_web
    restart: always
    entrypoint: /build/src/entrypoint.sh
    ports:
      - 8080:8080
    depends_on:
      - mydb