version: "3.4"
services:
  mydb:
    build:
      context: .
      target: db
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432

  web:
    build: 
      context: .
      target: web_api
    container_name: infinity_web
    restart: always
    entrypoint: /build/src/entrypoint.sh
    ports:
      - 8080:8080
    depends_on:
      - mydb

# Although I do not explicitly define the network for two containers,
# the docker still create the bridge network for me.

# docker network ls  -> you can see the created network
# docker network inspect network-name -> you can see how many containers in this network
# docker container inspect container-name --> you can see the network of this container